// <auto-generated />
using System;
using Blog.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230111112154_SeedCompled")]
    partial class SeedCompled
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Blog.Entity.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93a766de-4df0-4e68-80b2-3520b975d2a3"),
                            CategoryId = new Guid("a26ffa43-78a3-414b-89e7-83af238d4bd4"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nec erat varius, accumsan eros vitae, sodales risus. Vivamus volutpat tellus id sapien lacinia, vel fringilla leo condimentum. Curabitur accumsan, nunc sed pellentesque faucibus, dolor elit eleifend ligula, nec blandit dolor eros ut libero. Etiam a nulla quis urna accumsan placerat id in nisi. Donec et nibh leo. Donec tempus neque urna. Vivamus pulvinar erat egestas rutrum malesuada. Donec urna quam, tristique eu faucibus molestie, semper ut dui. Mauris vitae congue tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 1, 11, 14, 21, 54, 696, DateTimeKind.Local).AddTicks(6746),
                            ImageId = new Guid("34592e9f-8d43-4218-97b9-9b9e5a90a1a6"),
                            IsDeleted = false,
                            Title = "Asp.net Core Deneme Makalesi",
                            ViewCount = 15
                        },
                        new
                        {
                            Id = new Guid("21295476-2a13-4056-b076-1362c6629009"),
                            CategoryId = new Guid("98e0002d-19e4-446c-aa10-9c408632375d"),
                            Content = "Visual Studio Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque nec erat varius, accumsan eros vitae, sodales risus. Vivamus volutpat tellus id sapien lacinia, vel fringilla leo condimentum. Curabitur accumsan, nunc sed pellentesque faucibus, dolor elit eleifend ligula, nec blandit dolor eros ut libero. Etiam a nulla quis urna accumsan placerat id in nisi. Donec et nibh leo. Donec tempus neque urna. Vivamus pulvinar erat egestas rutrum malesuada. Donec urna quam, tristique eu faucibus molestie, semper ut dui. Mauris vitae congue tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 1, 11, 14, 21, 54, 696, DateTimeKind.Local).AddTicks(6753),
                            ImageId = new Guid("ffb69adc-97ed-448e-80ee-b4e8659f9a87"),
                            IsDeleted = false,
                            Title = "Visual Studio Deneme Makalesi",
                            ViewCount = 15
                        });
                });

            modelBuilder.Entity("Blog.Entity.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a26ffa43-78a3-414b-89e7-83af238d4bd4"),
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 1, 11, 14, 21, 54, 696, DateTimeKind.Local).AddTicks(6898),
                            IsDeleted = false,
                            Name = "Asp.Net Core"
                        },
                        new
                        {
                            Id = new Guid("98e0002d-19e4-446c-aa10-9c408632375d"),
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 1, 11, 14, 21, 54, 696, DateTimeKind.Local).AddTicks(6902),
                            IsDeleted = false,
                            Name = "Visual Studio 2022"
                        });
                });

            modelBuilder.Entity("Blog.Entity.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34592e9f-8d43-4218-97b9-9b9e5a90a1a6"),
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 1, 11, 14, 21, 54, 696, DateTimeKind.Local).AddTicks(6997),
                            FileName = "Images/testimage",
                            FileType = "jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("ffb69adc-97ed-448e-80ee-b4e8659f9a87"),
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 1, 11, 14, 21, 54, 696, DateTimeKind.Local).AddTicks(7000),
                            FileName = "Images/vstest",
                            FileType = "jpg",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Blog.Entity.Entities.Article", b =>
                {
                    b.HasOne("Blog.Entity.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Entity.Entities.Image", "Image")
                        .WithMany("Articles")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Blog.Entity.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Blog.Entity.Entities.Image", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
